version: '3.1'
services:
  db:
    container_name: cc-service-db
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: catalog_count
    ports:
      - 3306:3306
    volumes:
      - ./provision/cc-service-db/infra/docker.cnf:/etc/mysql/conf.d/docker.cnf
  flyway:
    container_name: cc-service-flyway
    platform: linux/x86_64
    image: flyway/flyway:6.5.5
    environment:
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - FLYWAY_URL=jdbc:mysql://db:3306/catalog_count?useUnicode=true&connectionCollation=utf8_unicode_ci&characterSetResults=utf8&characterEncoding=utf8&serverTimezone=UTC
    volumes:
      - ./flyway-db-configuration/flyway-6.5.5/sql:/flyway/sql
    command: migrate -connectRetries=60
    depends_on:
      - db
  app:
    container_name: cc-service-jetty-server-app
    image: cc-service-jetty-server-image
    ports:
      - 8080:8080
      - 8081:8081     # allow remote debug
    environment:
      - app_env=local
      - key=${CC_SERVICE_KEY}
      - JDBC_URL=jdbc:mysql://db:3306/catalog_count?useUnicode=true&connectionCollation=utf8_unicode_ci&characterSetResults=utf8&characterEncoding=utf8&serverTimezone=UTC
      - JDBC_USERNAME=root
      - JDBC_PASSWORD=$MYSQL_ROOT_PASSWORD
    build:
      context: .
    depends_on:
      - flyway