services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
    environment:
      ADMINER_DEFAULT_SERVER: cc-db

  cc-db:
    container_name: cc-service-db
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: catalog_count
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD}
      start_period: 5s
      timeout: 20s
      retries: 10
    volumes:
      - ./provision/cc-service-db/infra/docker.cnf:/etc/mysql/conf.d/docker.cnf

  cc-flyway:
    container_name: cc-service-flyway
    platform: linux/x86_64
    image: flyway/flyway:6.5.5
    environment:
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}
      FLYWAY_URL: ${DOCKER_JDBC_URL}
    volumes:
      - ./flyway-db-configuration/flyway-6.5.5/sql:/flyway/sql
    command: migrate -connectRetries=60
    depends_on:
      cc-db:
        condition: service_healthy

  cc-app:
    container_name: cc-service-jetty-server-app
    image: cc-service-jetty-server-image
    ports:
      - 8080:8080
      - 8081:8081     # allow remote debug
    environment:
      app_env: local
      key: ${CC_SERVICE_KEY}
      JDBC_URL: ${DOCKER_JDBC_URL}
      JDBC_USERNAME: ${JDBC_USER}
      JDBC_PASSWORD: $JDBC_PASSWORD
      CC_SERVICE_DEADLINE_DAY: ${CC_SERVICE_DEADLINE_DAY}
      CC_SERVICE_DEFAULT_EXPIRATION_SECS: ${CC_SERVICE_DEFAULT_EXPIRATION_SECS}
    build:
      context: .
    depends_on:
      - cc-flyway
