# This is a basic workflow that is manually triggered

name: ECS CatalogCount Service DesireCount

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '0 15 * * *' # runs at 3pm UTC, 8am PST

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  modify-desire-count:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      if: github.event.schedule == '0 15 * * *'
      run: echo "Hello I will change desire count to 0"
